# This file is Free Software under the Apache-2.0 License
# without warranty, see README.md and LICENSE for details.
#
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: 2025 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering:
# * 2025 Intevation GmbH <https://intevation.de>
# * 2025 Fraunhofer Institute for Applied an Integrated Security (AISEC) <https://aisec.fraunhofer.de>

# Logging configuration
#[log]
#file   = "contravider.log"
#level  = "INFO"        # Options: DEBUG, INFO, WARN, ERROR
#source = false
#json   = false

# Signing key
#[signing]
#key        = "privatekey.asc" # Used to sign the advisories.
#passphrase = ""

# Web server configuration
#[web]
#host      = "localhost"
#port      = 8083
#protocol  = "https"
#root      = "web"
#cert_file = "" # Set these two to the public/private key of the server
#key_file  = "" # if you want to run an HTTPS/TLS server.

[providers]
#git_url             = "https://github.com/csaf-testsuite/distribution.git"
#update              = "5m"
#base_url            = "{protocol}://{host}:{port}/{profile}"
#workdir             = "checkout"
# profiles: The following three types of identifiers are available for the classification of the profiles
# VALID_: This prefix indicates configurations that are set up correctly and comply with established requirements.
# STANDARD_ERROR_: This prefix is used for misconfigurations that do not meet the requirements of the CSAF standard.
# KNOWN_ISSUE_: This prefix designates misconfigurations that have already been identified in existing systems.
profiles.STANDARD_ERROR_VALID_CSAF_DOCUMENT = ["main", "7.1.1_Requirement_1_Valid_CSAF_Document"]
profiles.STANDARD_ERROR_FILENAME = ["main", "7.1.2_Requirement_2_Filename"]
profiles.STANDARD_ERROR_TLP_WHITE = ["main", "7.1.4_Requirement_4_TLP_WHITE"]
profiles.STANDARD_ERROR_TLP_AMBER_AND_TLP_RED = ["main", "7.1.5_Requirement_5_TLP_AMBER_and_TLP_RED"]
profiles.STANDARD_ERROR_ONE_FOLDER_PER_YEAR = ["main", "7.1.11_Requirement_11_One_Folder_per_Year"]
profiles.STANDARD_ERROR_INDEX_TXT   = ["main", "7.1.12_Requirement_12_index.txt"]
profiles.STANDARD_ERROR_CHANGES_CSV = ["main", "7.1.13_Requirement_13_changes.csv"]
profiles.STANDARD_ERROR_ROLIE_FEED = ["main", "7.1.15_Requirement_15_ROLIE_Feed"]
