# This file is Free Software under the Apache-2.0 License
# without warranty, see README.md and LICENSE for details.
#
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: 2025 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering:
# * 2025 Intevation GmbH <https://intevation.de>
# * 2025 Fraunhofer Institute for Applied an Integrated Security (AISEC) <https://aisec.fraunhofer.de>

# Logging configuration
#[log]
#file = "contravider.log"
#level = "DEBUG"        # Options: DEBUG, INFO, WARN, ERROR
#source = false
#json = false

# Signing key
#[signing]
#key        = "privatekey.asc"
#passphrase = ""

# Web server configuration
[web]
#host = "localhost"
#port = 8083
#root = "web"
username = "alice"
password = "secret"

[providers]
workdir              = "checkout"
profiles.index_txt   = ["main", "7.1.12_Requirement_12_index.txt"]
profiles.changes_csv = ["main", "7.1.13_Requirement_13_changes.csv"]
