# Logging configuration
#[log]
#file = "contravider.log"
#level = "DEBUG"        # Options: DEBUG, INFO, WARN, ERROR
#source = false
#json = false

# Web server configuration
[web]
host = "localhost"
port = 8443
root = "web"
tls_cert_file = "config/test_server.crt"
tls_key_file = "config/test_server.key"