# This file is Free Software under the Apache-2.0 License
# without warranty, see README.md and LICENSE for details.
#
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: 2025 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering:
# * 2025 Intevation GmbH <https://intevation.de>
# * 2025 Fraunhofer Institute for Applied an Integrated Security (AISEC) <https://aisec.fraunhofer.de>

name: Go

on:
  push:
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build
        run: go build -v ./cmd/...

      - name: vet
        run: go vet ./...

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: "-l -d"

      - name: golint
        uses: Jerome1337/golint-action@v1.0.3

      - name: Revive Action
        uses: morphy2k/revive-action@v2.7.4

      - name: Tests
        run: go test -v ./...
